services:
  bot:
    image: arlukmanova/tg-bot:latest
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://service:8000/predict
    env_file:
      - .env
    networks:
      - MyNet

  ui:
    image: arlukmanova/streamlit-app:latest
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://service:8000/predict
    networks:
      - MyNet
    ports:
      - "9000:8501"

  service:
    image: arlukmanova/classification-service:latest
    restart: on-failure
    env_file:
      - .env
    networks:
      - MyNet
    ports:
      - "9001:8000"

networks:
  MyNet:
    name: MyNet
