services:
  bot:
    build:
      context: ./tg-bot/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://service:8000/predict
    env_file:
      - .env
    networks:
      - MyNet

  ui:
    build:
      context: ./streamlit-app/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://service:8000/predict
    networks:
      - MyNet
    ports:
      - "9000:8501"

  service:
    build:
      context: ./classification-service
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    networks:
      - MyNet
    ports:
      - "9001:8000"



networks:
  MyNet:
    name: MyNet
