services:
  bot:
    image: arlukmanova/tg-bot:latest
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://api:8000/
    env_file:
      - .env
    networks:
      - MyNet

  ui:
    image: arlukmanova/streamlit-app:latest
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://api:8000/
    networks:
      - MyNet
    ports:
      - "9000:8501"

  api:
    image: arlukmanova/classification-service:latest
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - MyNet
    ports:
      - "9001:8000"
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000

  worker:
    image: arlukmanova/classification-service:latest
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AWS_ENDPOINT_URL=https://storage.yandexcloud.net
      - AWS_DEFAULT_REGION=ru-central1
    env_file:
      - .env
    networks:
      - MyNet
    command: celery -A worker.predict_task.celery_app worker --loglevel=info --concurrency=1
    deploy:
      replicas: 3

  redis:
    image: redis:5.0-alpine
    networks:
      - MyNet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure

  flower:
    image: mher/flower:latest
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    networks:
      - MyNet
    ports:
      - "5555:5555"
    command: celery flower

networks:
  MyNet:
    name: MyNet
