services:
  redis:
    image: redis:5.0-alpine
    networks:
      - MyNet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure

  bot:
    image: arlukmanova/tg-bot:latest
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://service:8000/predict
    env_file:
      - .env
    networks:
      - MyNet

  ui:
    image: arlukmanova/streamlit-app:latest
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://service:8000/
    networks:
      - MyNet
    ports:
      - "9000:8501"

  service:
    image: arlukmanova/classification-service:latest
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - MyNet
    ports:
      - "9001:8000"

  worker:
    image: arlukmanova/classification-service:latest
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    networks:
      - MyNet
    command: celery -A celery_app worker --loglevel=info --concurrency=1

  flower:
    image: mher/flower:latest
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    networks:
      - MyNet
    ports:
      - "5555:5555"
    command: celery flower

networks:
  MyNet:
    name: MyNet
