services:
  bot:
    build:
      context: ./tg-bot/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://localhost:8000/predict
    env_file:
      - .env
    networks:
      - MyNet

  ui:
    build:
      context: ./streamlit-app/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - PREDICTION_SERVICE_URL=http://localhost:8000/predict
    networks:
      - MyNet
    ports:
      - "8080:8501"



networks:
  MyNet:
    name: MyNet
