name: deploy classification-service

on:
  push:
    tags:
      - 'service/v*'
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-component.yml
    with:
      component-name: classification-service

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow, boto3, tqdm

      - name: Donload model from MLFlow Model Registry
        run: |
          python3 ./classification-service/worker/download_model.py ./classification-service/models ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Get version tag or commit hash
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/service/v* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/service/}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./classification-service
          file: ./classification-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_LOGIN }}/classification-service:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_LOGIN }}/classification-service:latest