name: deploy streamlit-app

on:
  push:
    tags:
      - 'web/v*'
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-component.yml
    with:
      component-name: streamlit-app

  build-and-push:
    needs: test-and-lint
    uses: ./.github/workflows/build-and-publish-component.yml
    with:
      component-name: streamlit-app
      git-tag-name: web
    secrets:
      DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH using appleboy/ssh-action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/xray/medical-image-processing
            docker compose pull
            docker compose up -d


