name: deploy tg-bot

on:
  push:
    tags:
      - 'bot/v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Get version tag or commit hash
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/bot/v* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/bot/}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./tg-bot/
          file: ./tg-bot/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_LOGIN }}/tg-bot:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_LOGIN }}/tg-bot:latest


