name: deploy classification-service

on:
  push:
    tags:
      - 'service/v*'
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-component.yml
    with:
      component-name: classification-service

  build-and-push:
    uses: ./.github/workflows/build-and-publish-component.yml
      with:
        component-name: classification-service
        git-tag-name: service