name: deploy streamlit-app

on:
  push:
    tags:
      - 'web/v*'
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-component.yml
    with:
      component-name: streamlit-app

  build-and-push:
    uses: ./.github/workflows/build-and-publish-component.yml
    with:
      component-name: streamlit-app
      git-tag-name: web
    secrets:
      DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}


