name: deploy tg-bot

on:
  push:
    tags:
      - 'bot/v*'
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-component.yml
    with:
      component-name: tg-bot

  build-and-push:
    uses: ./.github/workflows/build-and-publish-component.yml
    with:
      component-name: tg-bot
      git-tag-name: bot

