name: test and lint tg-bot 

on:
  push:
    branches:
      - '**'
    paths:
      - 'tg-bot/**'
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-component.yml
    with:
      component-name: tg-bot