name: test and lint classification-service 

on:
  push:
    branches:
      - '**'
    paths:
      - 'classification-service/**'
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint-component.yml
    with:
      component-name: classification-service